server:
  port: 4041
spring:
    application:
     name: Food_Project
     
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://${DB_HOST:localhost}:3306/dockFood?createDatabaseIfNotExist=true
        username: root
        password: 1234
        
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true